In [47]:
#definimos 2 matrices
#cuando hacemos un slicing, creamos una vista de la matriz original,
#si modificamos la vista, tambien modificaremos la matriz original.
ref: https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3])
y=np.array([2,4,6])

In [4]:
X=np.array([[1,2,3],
            [2,4,5]])
Y=np.array([[2,4,6],
            [8,10,12]])

In [5]:
x[2]

3

In [8]:
x[1:2]

array([2])

In [13]:
#suma directa o simple, elemento a elemento.
z=x+y

In [14]:
z

array([3, 6, 9])

In [25]:
X[:,1]

array([2, 4])

In [26]:
Y[:,1]

array([ 4, 10])

In [30]:
#convertir una secuencia(lista) en vector
list=[1,2,3,4]
a=np.array(list)

In [35]:
a[1:2]

array([2])

In [38]:
a=[1,2,3]
b=[4,5,6]
c=np.array([a,b])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
element1=c[1,2]

In [41]:
element1

6

In [42]:
#sumar la segunda fila de X y Y
suma=X[:,1]+Y[:,1]
suma

array([ 6, 14])

In [45]:
#suma de listas con suma de matrices
#listas
print("listas",[2,3]+[1,2])
#matrices
np.array([2,3])+np.array([1,2])

listas [2, 3, 1, 2]


array([3, 5])

In [49]:
#vista
vista=Y[:,2]
vista

array([ 6, 12])

In [58]:
vista[1:2]=0
#notamos que en la matriz original cambia un valor a cero.
Y

array([[ 2,  4,  6],
       [ 8, 10,  0]])

In [59]:
#matrices tridimensionales
#el primer indice indica la matriz i, (candida de matrices posicionadas)
#el segundo indica la fila j
#el tercero indica la columna k

In [60]:
a3=np.array([[[1,2]
              ,[2,3]],
             [[1,1],
              [2,3]
             ]])

In [61]:
a3.shape

(2, 2, 2)

In [66]:
#para traer la primera matriz
print(a3[0])

[[1 2]
 [2 3]]


In [67]:
#para traer la segunda matriz
print(a3[1])

[[1 1]
 [2 3]]


In [69]:
# traer todas las j=1
j1=a3[:,1,:]
j1

array([[2, 3],
       [2, 3]])

In [70]:
# traemos todas las columnas k=1
a3[:,:,1]

array([[2, 3],
       [1, 3]])

In [71]:
#ojo : Puede cortar una matriz numpy es una forma similar de cortar una lista, excepto que puede hacerlo en más de una dimensión.