In [1]:
import numpy as np

In [14]:
#generar una matriz donde sus elementos esten espaciados uniformemente entre un rango de 2 valores extremos
a=np.linspace(0,100,10)

In [11]:
a

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [15]:
# GENERAMOS UNA MATRIZ QUE ESTE ESPACIADO LOGARITMICAMENTE
# para eso los 2 valores extremos tendremos que convertirlos a valores logaritmicos

In [13]:
np.logspace(1,2,10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [17]:
#obtenemos 10 elementos espaciados logaritmicamente entre 250 y 500
np.logspace(np.log(250),np.log(500),10)

array([ 332246.8849859 ,  396713.76642775,  473689.35446895,
        565600.75179058,  675345.9992461 ,  806385.45343834,
        962850.8945679 , 1149675.80481174, 1372750.92501491,
       1639109.99452395])

In [18]:
# averiguar la dimension de una matriz

In [19]:
X=np.array([[1,2],
            [2,4]])

In [20]:
X.shape

(2, 2)

In [21]:
# numero de elementos

In [22]:
X.size

4

In [23]:
# numpy tiene su propio modulo para generar numeors aleatorios

In [24]:
x=np.random.random(10)

array([0.98737594, 0.15515676, 0.38202097, 0.14103611, 0.95868058,
       0.09425451, 0.19261701, 0.46285309, 0.81188131, 0.91041386])

In [28]:
#algunos valores , tal que:
np.any(X>0.9)

True

In [29]:
np.any(X>10)

False

In [31]:
# todos los valores
np.all(X>0.1)

True

In [32]:
np.all(X>2)

False

In [35]:
x = 20
not np.any([x%i == 0 for i in range(2, x)])

False