In [2]:
import numpy as np

In [10]:
z1=np.array([1,2,3,4,5,8,9])

In [11]:
z2=z1+1

In [12]:
z1

array([1, 2, 3, 4, 5, 8, 9])

In [13]:
z2

array([ 2,  3,  4,  5,  6,  9, 10])

In [14]:
#podemos extraer una matriz booleana de z1
z1>6

array([False, False, False, False, False,  True,  True])

In [16]:
#obtener solo los valores verdaderos
z1[z1>6]

array([8, 9])

In [25]:
#index en numpy: si indexamos una matriz, creamos una copia y no una vista,
# si cortamos la matriz con ":", entonces estaremos haciendo una vista de la matriz original.

In [18]:
z1=np.array([1,2,3,4,5])

In [23]:
ind=np.array([2,4])

In [24]:
z1[ind]

array([3, 5])

In [29]:
z1[3:] is ind
#por que el primero es una vista y el segundo una copia, tienen distintas direcciones de memoria.

False